---
title: "R Notebook for image classification"
output: html_notebook
---

Those are my notes to understand how to buld an image classifier in R. I am using the dogs and cats images from the Kaggle competition: https://www.kaggle.com/c/dogs-vs-cats and following this tutorial by  Dr. Bharatendra Rai: https://www.youtube.com/watch?v=iExh0qj2Ouo

First, loading the libraries:
```{r}
library(tensorflow) #machine learning
library(keras) #neural network
library(EBImage) #image processing
```

Setting up the environment and reading images: 
```{r}
setwd("/home/caroline/projects/dogs-vs-cats/data/raw/train")

pics <- c("cat.1.jpg", "cat.2.jpg", "cat.3.jpg", "cat.4.jpg", "cat.5.jpg", "cat.6.jpg", "dog.1.jpg", "dog.2.jpg", "dog.3.jpg", "dog.4.jpg", "dog.5.jpg", "dog.6.jpg")

mypic <- list()

for(i in 1:12) {
  mypic[[i]]<-readImage(pics[i])
}
```

Explore and dispplay images
```{r}
print(mypic[[1]])
display(mypic[[1]])
summary(mypic[[1]])
hist(mypic[[1]])
str(mypic)
```


Resize all pictures to have all dimensions
```{r}
for (i in 1:12) {mypic[[i]] <- resize(mypic[[i]], 28, 28)}
```

Explore resized images
```{r}
print(mypic[[1]])
display(mypic[[1]])
summary(mypic[[1]])
hist(mypic[[1]])
str(mypic)
```

